### ISSUE TITLE
Create new "terraform-ibm-ease" module

### ISSUE THREAD

**Issue by eamunoz** [terraform-ibm-modules/terraform-ibm-enterprise-app-java#3]
### Description

Create new "terraform-ibm-ease" module

### New  module

new "terraform-ibm-ease" module

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ChuckCox** [comment]
We added our code to the `dev` branch: https://github.com/terraform-ibm-modules/terraform-ibm-enterprise-app-java/pull/15

And the DA team continued the required work in the `draft_da` branch using our initial code changes: https://github.com/terraform-ibm-modules/terraform-ibm-enterprise-app-java/pull/17
